/* Generated By:JavaCC: Do not edit this line. KarloffConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface KarloffConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int APARENTESES = 8;
  /** RegularExpression Id. */
  int FPARENTESES = 9;
  /** RegularExpression Id. */
  int PONTOVIRG = 10;
  /** RegularExpression Id. */
  int VIRGULA = 11;
  /** RegularExpression Id. */
  int IGUAL = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int SOMA = 15;
  /** RegularExpression Id. */
  int SUB = 16;
  /** RegularExpression Id. */
  int MULT = 17;
  /** RegularExpression Id. */
  int DIV = 18;
  /** RegularExpression Id. */
  int MENOR = 19;
  /** RegularExpression Id. */
  int MAIOR = 20;
  /** RegularExpression Id. */
  int IGUALDADE = 21;
  /** RegularExpression Id. */
  int NEWVAR = 22;
  /** RegularExpression Id. */
  int FLOAT = 23;
  /** RegularExpression Id. */
  int BOOL = 24;
  /** RegularExpression Id. */
  int VOID = 25;
  /** RegularExpression Id. */
  int IF = 26;
  /** RegularExpression Id. */
  int THEN = 27;
  /** RegularExpression Id. */
  int WHILE = 28;
  /** RegularExpression Id. */
  int READ = 29;
  /** RegularExpression Id. */
  int RETURN = 30;
  /** RegularExpression Id. */
  int PRINT = 31;
  /** RegularExpression Id. */
  int VERDADEIRO = 32;
  /** RegularExpression Id. */
  int FALSO = 33;
  /** RegularExpression Id. */
  int FUNCAO = 34;
  /** RegularExpression Id. */
  int NUM = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "\"=\"",
    "\"&\"",
    "\"|\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"newVar\"",
    "\"float\"",
    "\"boolean\"",
    "\"void\"",
    "\"if\"",
    "\"then\"",
    "\"while\"",
    "\"readInput\"",
    "\"return\"",
    "\"printOut\"",
    "\"true\"",
    "\"false\"",
    "\"fun\"",
    "<NUM>",
    "<ID>",
  };

}
